server:
  port: 9091
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/javascript,text/css,application/javascript
  undertow:
   buffer-size: 512
   io-threads: 20
   worker-threads: 20
spring:
  http:
    multipart:
      maxFileSize: 1000Mb
      maxRequestSize: 1000Mb
  profiles:
    active: @profileActive@